function plot_density(filename)
    % This function can be used to plot the density of states of a
    % multilayer hybrid system, in the output format generated by
    % the accompanying program 'density'.
    
    % Load the file
    A = load(filename);
    
    % Convert the data to a Matlab-compatible format
    X = unique(A(:,1),'stable');
    Y = unique(A(:,2),'stable');
    Z = reshape(A(:,3), [length(Y),length(X)]);
    
    % Plot the data
    surf(Y,X,Z','EdgeColor','None')
    
    % Set the default viewer angle
    view(2)
    
    % Set the plot range
    xlim([-1.5,1.5])

    % Set the axis labels
    xlabel('Energy \epsilon/\Delta')
    ylabel('Position z/\xi')
        
    % Fix axis ticks
    set(gca, 'XTickLabel', num2str(get(gca,'XTick')','%3.1f'))
    set(gca, 'YTickLabel', num2str(get(gca,'YTick')','%3.1f'))
end